# Import local variables
imports:
    - { resource: config_local.yml }

# Application
app.config:
    charset:       UTF-8
    error_handler: null
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    validation: { enabled: true, annotations: true }
    templating:
        escaping: htmlspecialchars

# Services
doctrine.dbal:
    dbname:   alom
    user:     root
    password:
doctrine.orm: ~

blog.helper: ~
