# Import local variables
imports:
    - { resource: config_local.yml }


# Parameters
parameters:
    kernel.include_core_classes: false

# Services

kernel.config: ~

web.config:
    router: { resource: "%kernel.root_dir%/config/routing.yml" }

web.templating: ~

doctrine.orm: ~

blog.helper: ~
