imports:
    - { resource: config_dev.yml }

doctrine.dbal:
  dbname: alom_test

app.config:
    error_handler: false
    test: ~

webprofiler.config:
    toolbar: false
    intercept_redirects: true

zend.config:
    logger:
        priority: debug
