imports:
    - { resource: config_dev.yml }

doctrine.dbal:
    driverClass: PDOSQLite
    path:        "%kernel.root_dir%/db_test.sqlite"

app.config:
    error_handler: false
    test: ~

webprofiler.config:
    toolbar: false
    intercept_redirects: true

zend.config:
    logger:
        priority: debug
