# Parameters
parameters:
    kernel.include_core_classes: false

# Services
doctrine.dbal:
    driver:   PDOSQLite
    path:     "%kernel.root_dir%/db.sqlite"

kernel.config: ~

web.config:
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:
      enabled: true

web.templating: ~

doctrine.orm: ~

blog.helper: ~
