imports:
    - { resource: config.yml }

doctrine.dbal:
    driver:   PDOSQLite
    path:     "%kernel.root_dir%/db_test.sqlite"

zend.logger:
    priority: debug
    path:     %kernel.root_dir%/logs/%kernel.environment%.log

kernel.test: ~
