_esi:
    resource:  "FrameworkBundle/Resources/config/routing/internal.xml"
    prefix:    "/_esi"

_contact:
    resource:  "ContactBundle/Resources/config/routing/main.xml"
    prefix:    "/contact"

# Page
page_main_homepage:
    pattern:  /
    defaults: { _controller: MainBundle:Main:homepage }

# Identity
identity_main_cv:
    pattern:  /cv
    defaults: { _controller: IdentityBundle:Main:cv }

identity_main_contact:
    pattern:  /contact
    defaults: { _controller: IdentityBundle:Main:contact }

identity_main_cv:
    pattern:  /cv
    defaults: { _controller: IdentityBundle:Main:cv }

# Blog

blog_post_view:
    pattern:  /blog/:slug
    defaults: { _controller: BlogBundle:Post:view }

blog_post_list:
    pattern:  /blog
    defaults: { _controller: BlogBundle:Post:list }

blog_post_list_year:
    pattern:  /blog/year/:year
    defaults: { _controller: BlogBundle:Post:list }
