imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

parameters:
    test.client.class: Alom\Website\MainBundle\Test\Client
    rss_address:       http://feeds.feedburner.com/AlexandreSalome
    rss_title:         "Blog posts from the alexandre-salome.fr"

framework:
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    form:
      resources: [ "::forms.html.twig" ]
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: gmail
    username:  %mailer_user%
    password:  %mailer_password%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        yui_js:     { jar: %yui_compiler_path% }
        yui_css:    { jar: %yui_compiler_path% }
        compass:
          calls:
            - [ "setImagesDir", [ %kernel.root_dir%/../web/images ] ]
            - [ "setHttpPath",  [ /images ] ]
