# Homepage
alom_website_main_homepage:
    pattern: /
    defaults: { _controller: "AlomWebsiteBundle:Main:homepage" }

alom_website_main_sitemap:
    pattern: /sitemap.xml
    defaults: { _controller: "AlomWebsiteBundle:Main:sitemap" }

# Post

alom_website_post_list:
    pattern: /blog
    defaults: { _controller: "AlomWebsiteBundle:Post:list" }

alom_website_post_rss:
    pattern: /rss/{token}
    defaults: { _controller: "AlomWebsiteBundle:Post:rss" }

alom_website_post_markdownPreview:
    pattern: /blog/markdown-preview
    defaults: { _controller: "AlomWebsiteBundle:Post:markdownPreview" }

alom_website_post_view:
    pattern: /blog/{slug}
    defaults: { _controller: "AlomWebsiteBundle:Post:view" }

alom_website_post_create:
    pattern: /blog/create
    defaults: { _controller: "AlomWebsiteBundle:Post:edit" }

alom_website_post_edit:
    pattern: /blog/{id}/edit
    defaults: { _controller: "AlomWebsiteBundle:Post:edit" }

alom_website_post_enable:
    pattern: /blog/{id}/enable
    defaults: { _controller: "AlomWebsiteBundle:Post:enable" }

alom_website_post_disable:
    pattern: /blog/{id}/disable
    defaults: { _controller: "AlomWebsiteBundle:Post:disable" }

alom_website_post_delete:
    pattern: /blog/{id}/delete
    defaults: { _controller: "AlomWebsiteBundle:Post:delete" }

alom_website_post_delete:
    pattern: /blog/{id}/delete
    defaults: { _controller: "AlomWebsiteBundle:Post:delete" }

# Post Comment

alom_website_post_comment_delete:
    pattern: /blog/comment/{id}/delete
    defaults: {_controller: "AlomWebsiteBundle:PostComment:delete" }

alom_website_post_comment_list:
    pattern: /blog/comment/list
    defaults: {_controller: "AlomWebsiteBundle:PostComment:list" }

alom_website_post_comment_activate:
    pattern: /blog/comment/{id}/activate
    defaults: {_controller: "AlomWebsiteBundle:PostComment:activate" }

alom_website_post_comment_inactivate:
    pattern: /blog/comment/{id}/inactivate
    defaults: {_controller: "AlomWebsiteBundle:PostComment:inactivate" }

# Book

alom_website_book_list:
    pattern: /books
    defaults: {_controller: "AlomWebsiteBundle:Book:list" }

alom_website_book_create:
    pattern: /books/create
    defaults: {_controller: "AlomWebsiteBundle:Book:edit" }

alom_website_book_edit:
    pattern: /books/edit/{id}
    defaults: { _controller: "AlomWebsiteBundle:Book:edit" }

alom_website_book_delete:
    pattern: /books/delete/{id}
    defaults: { _controller: "AlomWebsiteBundle:Book:delete" }

alom_website_book_enable:
    pattern: /books/enable/{id}
    defaults: { _controller: "AlomWebsiteBundle:Book:enable" }

alom_website_book_disable:
    pattern: /books/disable/{id}
    defaults: { _controller: "AlomWebsiteBundle:Book:disable" }

# Identity

alom_website_identity_cv:
    pattern: /cv
    defaults: { _controller: "AlomWebsiteBundle:Identity:cv" }

alom_website_identity_contact:
    pattern: /contact
    defaults: { _controller: "AlomWebsiteBundle:Identity:contact" }

# Security

alom_website_security_login:
    pattern: /login
    defaults: { _controller: "AlomWebsiteBundle:Security:login" }

alom_website_security_check:
    pattern: /login_check
    defaults: { _controller: "AlomWebsiteBundle:Security:check" }

alom_website_security_logout:
    pattern: /logout
    defaults: { _controller: "AlomWebsiteBundle:Security:logout" }
